spring:
  messages:
    basename: i18n/application-messages
    cache-duration: -1
    encoding: UTF-8
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/oshiel_db
    username: admin
    password: admin_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true