spring:
  messages:
    basename: i18n/application-messages
    cache-duration: -1
    encoding: UTF-8
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/oshiel_db
    username: admin
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
slack:
  client:
    id: ${SLACK_CLIENT_ID}
    secret: ${SLACK_CLIENT_SECRET}
news:
  api:
    key: ${NEWS_API_KEY}
    endpoint: ${NEWS_API_ENDPOINT}
