spring:
  messages:
    basename: i18n/application-messages
    cache-duration: -1
    encoding: UTF-8
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/oshiel_db
    username: admin
    password: admin_password
    driver-class-name: com.mysql.cj.jdbc.Driver
doma:
  dialect: mysql
  data-source-name: jdbc:mysql://localhost:3306/oshiel_db?user=admin&password=admin_password
  exception-sql-log-type: formatted
  jdbc-logger: slf4j